version: "3.4"
services:
  php-fpm:
    image: php-dev:latest
    user: root    
    build:  
      dockerfile: ./docker/php/Dockerfile
      context: .
    restart: always    
    container_name: php-fpm        
    volumes:
      - ./:/var/www/html/:rw
      
  nginx:
    image: nginx:dev
    restart: always
    container_name: nginx    
    build:  
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    ports:
      - "80:80"
      - "443:443"        
    volumes:
      - ./:/var/www/html/:rw        

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    container_name: mysql
    env_file:
      - .env-mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql 
  
volumes:
  mysql_data: